[package]
name = "inkscape-shortcuter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = "0.11.0"
lazy_static = "1.4.0"
clipboard = "0.5.0"
anyhow = "1.0.68"
